# Generated by Django 4.2.7 on 2023-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spets', models.CharField(blank=True, max_length=100, null=True)),
                ('products', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('name_company', models.CharField(blank=True, max_length=100, null=True)),
                ('name_website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
