# Generated by Django 4.2.7 on 2023-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Лого сайта')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('locate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на whatsapp')),
                ('telegram', models.URLField(verbose_name='Ссылка на telegram')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.DeleteModel(
            name='QuizData',
        ),
    ]
