# Generated by Django 4.2.7 on 2023-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_index_delete_quizdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на telegram'),
        ),
    ]
