# Generated by Django 4.2.7 on 2023-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_index_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
