# Generated by Django 4.2.7 on 2023-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_index_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Оставленная заявка',
                'verbose_name_plural': 'Оставленные заявки',
            },
        ),
    ]
